// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/messages.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestHeader struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	SessionId            uint64   `protobuf:"varint,2,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Id                   int32    `protobuf:"zigzag32,3,opt,name=Id,proto3" json:"Id,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{0}
}
func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (dst *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(dst, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RequestHeader) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RequestHeader) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestHeader) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

// used by server for obtaining Status Code
// from request messages sent from client
// to parse response into suitable object
type GenericRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GenericRequest) Reset()         { *m = GenericRequest{} }
func (m *GenericRequest) String() string { return proto.CompactTextString(m) }
func (*GenericRequest) ProtoMessage()    {}
func (*GenericRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{1}
}
func (m *GenericRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericRequest.Unmarshal(m, b)
}
func (m *GenericRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericRequest.Marshal(b, m, deterministic)
}
func (dst *GenericRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericRequest.Merge(dst, src)
}
func (m *GenericRequest) XXX_Size() int {
	return xxx_messageInfo_GenericRequest.Size(m)
}
func (m *GenericRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenericRequest proto.InternalMessageInfo

func (m *GenericRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SignedRequest struct {
	RequestData          []byte   `protobuf:"bytes,1,opt,name=RequestData,proto3" json:"RequestData,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedRequest) Reset()         { *m = SignedRequest{} }
func (m *SignedRequest) String() string { return proto.CompactTextString(m) }
func (*SignedRequest) ProtoMessage()    {}
func (*SignedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{2}
}
func (m *SignedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedRequest.Unmarshal(m, b)
}
func (m *SignedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedRequest.Marshal(b, m, deterministic)
}
func (dst *SignedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedRequest.Merge(dst, src)
}
func (m *SignedRequest) XXX_Size() int {
	return xxx_messageInfo_SignedRequest.Size(m)
}
func (m *SignedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignedRequest proto.InternalMessageInfo

func (m *SignedRequest) GetRequestData() []byte {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (m *SignedRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// for broadcasting our LTPK
// to initiate DiceMix Run
// Code - C_LTPK_REQUEST
type LtpkExchangeRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	PublicKey            []byte         `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LtpkExchangeRequest) Reset()         { *m = LtpkExchangeRequest{} }
func (m *LtpkExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*LtpkExchangeRequest) ProtoMessage()    {}
func (*LtpkExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{3}
}
func (m *LtpkExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LtpkExchangeRequest.Unmarshal(m, b)
}
func (m *LtpkExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LtpkExchangeRequest.Marshal(b, m, deterministic)
}
func (dst *LtpkExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LtpkExchangeRequest.Merge(dst, src)
}
func (m *LtpkExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_LtpkExchangeRequest.Size(m)
}
func (m *LtpkExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LtpkExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LtpkExchangeRequest proto.InternalMessageInfo

func (m *LtpkExchangeRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LtpkExchangeRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

// For broadcasting our public key
// to initiate KeyExchange
// Code - C_KEY_EXCHANGE
type KeyExchangeRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	PublicKey            []byte         `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	NumMsgs              uint32         `protobuf:"varint,3,opt,name=NumMsgs,proto3" json:"NumMsgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *KeyExchangeRequest) Reset()         { *m = KeyExchangeRequest{} }
func (m *KeyExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeRequest) ProtoMessage()    {}
func (*KeyExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{4}
}
func (m *KeyExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeRequest.Unmarshal(m, b)
}
func (m *KeyExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeRequest.Marshal(b, m, deterministic)
}
func (dst *KeyExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeRequest.Merge(dst, src)
}
func (m *KeyExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeRequest.Size(m)
}
func (m *KeyExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeRequest proto.InternalMessageInfo

func (m *KeyExchangeRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *KeyExchangeRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *KeyExchangeRequest) GetNumMsgs() uint32 {
	if m != nil {
		return m.NumMsgs
	}
	return 0
}

// For broadcasting our DC Exponential Vector
// to initiate DC-EXP
// Code - C_EXP_DC_VECTOR
type DCExpRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	DCExpVector          []uint64       `protobuf:"varint,2,rep,packed,name=DCExpVector,proto3" json:"DCExpVector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DCExpRequest) Reset()         { *m = DCExpRequest{} }
func (m *DCExpRequest) String() string { return proto.CompactTextString(m) }
func (*DCExpRequest) ProtoMessage()    {}
func (*DCExpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{5}
}
func (m *DCExpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCExpRequest.Unmarshal(m, b)
}
func (m *DCExpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCExpRequest.Marshal(b, m, deterministic)
}
func (dst *DCExpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCExpRequest.Merge(dst, src)
}
func (m *DCExpRequest) XXX_Size() int {
	return xxx_messageInfo_DCExpRequest.Size(m)
}
func (m *DCExpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DCExpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DCExpRequest proto.InternalMessageInfo

func (m *DCExpRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DCExpRequest) GetDCExpVector() []uint64 {
	if m != nil {
		return m.DCExpVector
	}
	return nil
}

// For broadcasting our DC Simple Vector
// to initiate DC-SIMPLE
// C_SIMPLE_DC_VECTOR
type DCSimpleRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	DCSimpleVector       [][]byte       `protobuf:"bytes,2,rep,name=DCSimpleVector,proto3" json:"DCSimpleVector,omitempty"`
	MyOk                 bool           `protobuf:"varint,3,opt,name=MyOk,proto3" json:"MyOk,omitempty"`
	NextPublicKey        []byte         `protobuf:"bytes,4,opt,name=NextPublicKey,proto3" json:"NextPublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DCSimpleRequest) Reset()         { *m = DCSimpleRequest{} }
func (m *DCSimpleRequest) String() string { return proto.CompactTextString(m) }
func (*DCSimpleRequest) ProtoMessage()    {}
func (*DCSimpleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{6}
}
func (m *DCSimpleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCSimpleRequest.Unmarshal(m, b)
}
func (m *DCSimpleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCSimpleRequest.Marshal(b, m, deterministic)
}
func (dst *DCSimpleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCSimpleRequest.Merge(dst, src)
}
func (m *DCSimpleRequest) XXX_Size() int {
	return xxx_messageInfo_DCSimpleRequest.Size(m)
}
func (m *DCSimpleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DCSimpleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DCSimpleRequest proto.InternalMessageInfo

func (m *DCSimpleRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DCSimpleRequest) GetDCSimpleVector() [][]byte {
	if m != nil {
		return m.DCSimpleVector
	}
	return nil
}

func (m *DCSimpleRequest) GetMyOk() bool {
	if m != nil {
		return m.MyOk
	}
	return false
}

func (m *DCSimpleRequest) GetNextPublicKey() []byte {
	if m != nil {
		return m.NextPublicKey
	}
	return nil
}

// For broadcasting our confirmation for messages
// C_TX_CONFIRMATION
type ConfirmationRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Confirmation         bool           `protobuf:"varint,2,opt,name=Confirmation,proto3" json:"Confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfirmationRequest) Reset()         { *m = ConfirmationRequest{} }
func (m *ConfirmationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmationRequest) ProtoMessage()    {}
func (*ConfirmationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{7}
}
func (m *ConfirmationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationRequest.Unmarshal(m, b)
}
func (m *ConfirmationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationRequest.Marshal(b, m, deterministic)
}
func (dst *ConfirmationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationRequest.Merge(dst, src)
}
func (m *ConfirmationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmationRequest.Size(m)
}
func (m *ConfirmationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationRequest proto.InternalMessageInfo

func (m *ConfirmationRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ConfirmationRequest) GetConfirmation() bool {
	if m != nil {
		return m.Confirmation
	}
	return false
}

// For broadcasting our KESK
// to initiate BLAME
type InitiaiteKESKResponse struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	PrivateKey           []byte         `protobuf:"bytes,2,opt,name=PrivateKey,proto3" json:"PrivateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InitiaiteKESKResponse) Reset()         { *m = InitiaiteKESKResponse{} }
func (m *InitiaiteKESKResponse) String() string { return proto.CompactTextString(m) }
func (*InitiaiteKESKResponse) ProtoMessage()    {}
func (*InitiaiteKESKResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{8}
}
func (m *InitiaiteKESKResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiaiteKESKResponse.Unmarshal(m, b)
}
func (m *InitiaiteKESKResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiaiteKESKResponse.Marshal(b, m, deterministic)
}
func (dst *InitiaiteKESKResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiaiteKESKResponse.Merge(dst, src)
}
func (m *InitiaiteKESKResponse) XXX_Size() int {
	return xxx_messageInfo_InitiaiteKESKResponse.Size(m)
}
func (m *InitiaiteKESKResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiaiteKESKResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitiaiteKESKResponse proto.InternalMessageInfo

func (m *InitiaiteKESKResponse) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *InitiaiteKESKResponse) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

type ResponseHeader struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	SessionId            uint64   `protobuf:"varint,2,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Err                  string   `protobuf:"bytes,5,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{9}
}
func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (dst *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(dst, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseHeader) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *ResponseHeader) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ResponseHeader) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseHeader) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// for obtaining Status Code from response messages from server
// to parse response into suitable object
type GenericResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{10}
}
func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (dst *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(dst, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// Response returned by server when attempt to join dicemix
// S_JOIN_RESPONSE
type RegisterResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Id                   int32           `protobuf:"zigzag32,2,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{11}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RegisterResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Response returned by server for -
// StartDiceMix - Code S_START_DICEMIX
// KeyExchangeResponse - Code S_KEY_EXCHANGE
// DCSimpleResponse - Code S_SIMPLE_DC_VECTOR
// ConfirmationRequest - Code S_TX_CONFIRMATION
type DiceMixResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Peers                []*PeersInfo    `protobuf:"bytes,2,rep,name=Peers,proto3" json:"Peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DiceMixResponse) Reset()         { *m = DiceMixResponse{} }
func (m *DiceMixResponse) String() string { return proto.CompactTextString(m) }
func (*DiceMixResponse) ProtoMessage()    {}
func (*DiceMixResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{12}
}
func (m *DiceMixResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiceMixResponse.Unmarshal(m, b)
}
func (m *DiceMixResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiceMixResponse.Marshal(b, m, deterministic)
}
func (dst *DiceMixResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiceMixResponse.Merge(dst, src)
}
func (m *DiceMixResponse) XXX_Size() int {
	return xxx_messageInfo_DiceMixResponse.Size(m)
}
func (m *DiceMixResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiceMixResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiceMixResponse proto.InternalMessageInfo

func (m *DiceMixResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DiceMixResponse) GetPeers() []*PeersInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

// Response against DCExpRequest
// conatins ROOTS calculated by server using FLINT
// Code - S_EXP_DC_VECTOR
type DCExpResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Roots                []uint64        `protobuf:"varint,2,rep,packed,name=Roots,proto3" json:"Roots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DCExpResponse) Reset()         { *m = DCExpResponse{} }
func (m *DCExpResponse) String() string { return proto.CompactTextString(m) }
func (*DCExpResponse) ProtoMessage()    {}
func (*DCExpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{13}
}
func (m *DCExpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCExpResponse.Unmarshal(m, b)
}
func (m *DCExpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCExpResponse.Marshal(b, m, deterministic)
}
func (dst *DCExpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCExpResponse.Merge(dst, src)
}
func (m *DCExpResponse) XXX_Size() int {
	return xxx_messageInfo_DCExpResponse.Size(m)
}
func (m *DCExpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DCExpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DCExpResponse proto.InternalMessageInfo

func (m *DCExpResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DCExpResponse) GetRoots() []uint64 {
	if m != nil {
		return m.Roots
	}
	return nil
}

// Response against DCSimpleResponse
// conatins messages resolved via DC-SIMPLE vectors
// Code - S_SIMPLE_DC_VECTOR
type DCSimpleResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Messages             [][]byte        `protobuf:"bytes,2,rep,name=Messages,proto3" json:"Messages,omitempty"`
	Peers                []*PeersInfo    `protobuf:"bytes,3,rep,name=Peers,proto3" json:"Peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DCSimpleResponse) Reset()         { *m = DCSimpleResponse{} }
func (m *DCSimpleResponse) String() string { return proto.CompactTextString(m) }
func (*DCSimpleResponse) ProtoMessage()    {}
func (*DCSimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{14}
}
func (m *DCSimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCSimpleResponse.Unmarshal(m, b)
}
func (m *DCSimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCSimpleResponse.Marshal(b, m, deterministic)
}
func (dst *DCSimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCSimpleResponse.Merge(dst, src)
}
func (m *DCSimpleResponse) XXX_Size() int {
	return xxx_messageInfo_DCSimpleResponse.Size(m)
}
func (m *DCSimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DCSimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DCSimpleResponse proto.InternalMessageInfo

func (m *DCSimpleResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DCSimpleResponse) GetMessages() [][]byte {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *DCSimpleResponse) GetPeers() []*PeersInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

// Possible response against ConfirmationRequest
// only when all peers send valid confirmations to server
// Code - S_TX_SUCCESSFUL
type TXDoneResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TXDoneResponse) Reset()         { *m = TXDoneResponse{} }
func (m *TXDoneResponse) String() string { return proto.CompactTextString(m) }
func (*TXDoneResponse) ProtoMessage()    {}
func (*TXDoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{15}
}
func (m *TXDoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXDoneResponse.Unmarshal(m, b)
}
func (m *TXDoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXDoneResponse.Marshal(b, m, deterministic)
}
func (dst *TXDoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXDoneResponse.Merge(dst, src)
}
func (m *TXDoneResponse) XXX_Size() int {
	return xxx_messageInfo_TXDoneResponse.Size(m)
}
func (m *TXDoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TXDoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TXDoneResponse proto.InternalMessageInfo

func (m *TXDoneResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// message sent by server
// to initiate KESK
type InitiaiteKESK struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InitiaiteKESK) Reset()         { *m = InitiaiteKESK{} }
func (m *InitiaiteKESK) String() string { return proto.CompactTextString(m) }
func (*InitiaiteKESK) ProtoMessage()    {}
func (*InitiaiteKESK) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{16}
}
func (m *InitiaiteKESK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiaiteKESK.Unmarshal(m, b)
}
func (m *InitiaiteKESK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiaiteKESK.Marshal(b, m, deterministic)
}
func (dst *InitiaiteKESK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiaiteKESK.Merge(dst, src)
}
func (m *InitiaiteKESK) XXX_Size() int {
	return xxx_messageInfo_InitiaiteKESK.Size(m)
}
func (m *InitiaiteKESK) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiaiteKESK.DiscardUnknown(m)
}

var xxx_messageInfo_InitiaiteKESK proto.InternalMessageInfo

func (m *InitiaiteKESK) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// Sub-message for DiceMixResponse
type PeersInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	LTPublicKey          []byte   `protobuf:"bytes,2,opt,name=LTPublicKey,proto3" json:"LTPublicKey,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,4,opt,name=PrivateKey,proto3" json:"PrivateKey,omitempty"`
	NextPublicKey        []byte   `protobuf:"bytes,5,opt,name=NextPublicKey,proto3" json:"NextPublicKey,omitempty"`
	NumMsgs              uint32   `protobuf:"varint,6,opt,name=NumMsgs,proto3" json:"NumMsgs,omitempty"`
	DCVector             []uint64 `protobuf:"varint,7,rep,packed,name=DCVector,proto3" json:"DCVector,omitempty"`
	DCSimpleVector       [][]byte `protobuf:"bytes,8,rep,name=DCSimpleVector,proto3" json:"DCSimpleVector,omitempty"`
	OK                   bool     `protobuf:"varint,9,opt,name=OK,proto3" json:"OK,omitempty"`
	Messages             [][]byte `protobuf:"bytes,10,rep,name=Messages,proto3" json:"Messages,omitempty"`
	Confirmation         bool     `protobuf:"varint,11,opt,name=Confirmation,proto3" json:"Confirmation,omitempty"`
	MessageReceived      bool     `protobuf:"varint,12,opt,name=MessageReceived,proto3" json:"MessageReceived,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersInfo) Reset()         { *m = PeersInfo{} }
func (m *PeersInfo) String() string { return proto.CompactTextString(m) }
func (*PeersInfo) ProtoMessage()    {}
func (*PeersInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ccb5dc8f6ef7098f, []int{17}
}
func (m *PeersInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersInfo.Unmarshal(m, b)
}
func (m *PeersInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersInfo.Marshal(b, m, deterministic)
}
func (dst *PeersInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersInfo.Merge(dst, src)
}
func (m *PeersInfo) XXX_Size() int {
	return xxx_messageInfo_PeersInfo.Size(m)
}
func (m *PeersInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeersInfo proto.InternalMessageInfo

func (m *PeersInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PeersInfo) GetLTPublicKey() []byte {
	if m != nil {
		return m.LTPublicKey
	}
	return nil
}

func (m *PeersInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PeersInfo) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *PeersInfo) GetNextPublicKey() []byte {
	if m != nil {
		return m.NextPublicKey
	}
	return nil
}

func (m *PeersInfo) GetNumMsgs() uint32 {
	if m != nil {
		return m.NumMsgs
	}
	return 0
}

func (m *PeersInfo) GetDCVector() []uint64 {
	if m != nil {
		return m.DCVector
	}
	return nil
}

func (m *PeersInfo) GetDCSimpleVector() [][]byte {
	if m != nil {
		return m.DCSimpleVector
	}
	return nil
}

func (m *PeersInfo) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *PeersInfo) GetMessages() [][]byte {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PeersInfo) GetConfirmation() bool {
	if m != nil {
		return m.Confirmation
	}
	return false
}

func (m *PeersInfo) GetMessageReceived() bool {
	if m != nil {
		return m.MessageReceived
	}
	return false
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "messages.RequestHeader")
	proto.RegisterType((*GenericRequest)(nil), "messages.GenericRequest")
	proto.RegisterType((*SignedRequest)(nil), "messages.SignedRequest")
	proto.RegisterType((*LtpkExchangeRequest)(nil), "messages.LtpkExchangeRequest")
	proto.RegisterType((*KeyExchangeRequest)(nil), "messages.KeyExchangeRequest")
	proto.RegisterType((*DCExpRequest)(nil), "messages.DCExpRequest")
	proto.RegisterType((*DCSimpleRequest)(nil), "messages.DCSimpleRequest")
	proto.RegisterType((*ConfirmationRequest)(nil), "messages.ConfirmationRequest")
	proto.RegisterType((*InitiaiteKESKResponse)(nil), "messages.InitiaiteKESKResponse")
	proto.RegisterType((*ResponseHeader)(nil), "messages.ResponseHeader")
	proto.RegisterType((*GenericResponse)(nil), "messages.GenericResponse")
	proto.RegisterType((*RegisterResponse)(nil), "messages.RegisterResponse")
	proto.RegisterType((*DiceMixResponse)(nil), "messages.DiceMixResponse")
	proto.RegisterType((*DCExpResponse)(nil), "messages.DCExpResponse")
	proto.RegisterType((*DCSimpleResponse)(nil), "messages.DCSimpleResponse")
	proto.RegisterType((*TXDoneResponse)(nil), "messages.TXDoneResponse")
	proto.RegisterType((*InitiaiteKESK)(nil), "messages.InitiaiteKESK")
	proto.RegisterType((*PeersInfo)(nil), "messages.PeersInfo")
}

func init() { proto.RegisterFile("messages/messages.proto", fileDescriptor_messages_ccb5dc8f6ef7098f) }

var fileDescriptor_messages_ccb5dc8f6ef7098f = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x6f, 0x12, 0x41,
	0x14, 0xcd, 0x2e, 0xd0, 0xc2, 0x85, 0x85, 0xba, 0xd5, 0x74, 0x63, 0x8c, 0xd9, 0x4c, 0x8c, 0xc1,
	0x97, 0xd6, 0xd4, 0x5f, 0x50, 0x81, 0x28, 0xa1, 0x94, 0x66, 0x20, 0xea, 0xeb, 0x96, 0xbd, 0xa5,
	0x63, 0xcb, 0x0e, 0xee, 0x0c, 0x0d, 0x7d, 0xf0, 0x17, 0xe8, 0xcf, 0xf0, 0x4f, 0xfa, 0x66, 0x76,
	0x98, 0xfd, 0x6c, 0x13, 0xe3, 0x36, 0xbe, 0xcd, 0x3d, 0x99, 0x3d, 0xe7, 0xde, 0xbd, 0x7b, 0x0e,
	0xc0, 0xc1, 0x12, 0x85, 0xf0, 0x16, 0x28, 0x8e, 0xe2, 0xc3, 0xe1, 0x2a, 0xe4, 0x92, 0xdb, 0xf5,
	0xb8, 0x26, 0x1c, 0x2c, 0x8a, 0xdf, 0xd6, 0x28, 0xe4, 0x47, 0xf4, 0x7c, 0x0c, 0x6d, 0x1b, 0xaa,
	0x3d, 0xee, 0xa3, 0x63, 0xb8, 0x46, 0xd7, 0xa2, 0xea, 0x6c, 0xbf, 0x80, 0xc6, 0x14, 0x85, 0x60,
	0x3c, 0x18, 0xfa, 0x8e, 0xe9, 0x1a, 0xdd, 0x2a, 0x4d, 0x01, 0xbb, 0x0d, 0xe6, 0xd0, 0x77, 0x2a,
	0xae, 0xd1, 0x7d, 0x42, 0xcd, 0xa1, 0x1f, 0xdd, 0x9e, 0xb1, 0x25, 0x0a, 0xe9, 0x2d, 0x57, 0x4e,
	0xd5, 0x35, 0xba, 0x0d, 0x9a, 0x02, 0xe4, 0x04, 0xda, 0x1f, 0x30, 0xc0, 0x90, 0xcd, 0xb5, 0xae,
	0x7d, 0x04, 0x3b, 0x5b, 0x6d, 0xa5, 0xd9, 0x3c, 0x3e, 0x38, 0x4c, 0xba, 0xcd, 0xb5, 0x46, 0xf5,
	0x35, 0x32, 0x01, 0x6b, 0xca, 0x16, 0x01, 0xfa, 0x31, 0x83, 0x0b, 0x4d, 0x7d, 0xec, 0x7b, 0xd2,
	0x53, 0x34, 0x2d, 0x9a, 0x85, 0xd4, 0x04, 0x6c, 0x11, 0x78, 0x72, 0x1d, 0xa2, 0x9a, 0xa0, 0x45,
	0x53, 0x80, 0xf8, 0xb0, 0x7f, 0x2a, 0x57, 0xd7, 0x83, 0xcd, 0xfc, 0xca, 0x0b, 0x16, 0x58, 0xb6,
	0xb1, 0x48, 0xe5, 0x7c, 0x7d, 0x71, 0xc3, 0xe6, 0x23, 0xbc, 0x8b, 0x55, 0x12, 0x80, 0x7c, 0x07,
	0x7b, 0x84, 0x77, 0xff, 0x57, 0xc4, 0x76, 0x60, 0xf7, 0x6c, 0xbd, 0x1c, 0x8b, 0x85, 0x50, 0x1b,
	0xb1, 0x68, 0x5c, 0x12, 0x0f, 0x5a, 0xfd, 0xde, 0x60, 0xb3, 0x2a, 0x2d, 0xec, 0x42, 0x53, 0x11,
	0x7c, 0xc2, 0xb9, 0xe4, 0xa1, 0x63, 0xba, 0x95, 0x6e, 0x95, 0x66, 0x21, 0xf2, 0xcb, 0x80, 0x4e,
	0xbf, 0x37, 0x65, 0xcb, 0xd5, 0x4d, 0xf9, 0xf9, 0x5e, 0x43, 0x3b, 0xe6, 0xc8, 0x28, 0xb5, 0x68,
	0x01, 0x8d, 0x3e, 0xd4, 0xf1, 0xdd, 0xe4, 0x5a, 0x8d, 0x59, 0xa7, 0xea, 0x6c, 0xbf, 0x02, 0xeb,
	0x0c, 0x37, 0x32, 0x7d, 0x3f, 0x55, 0xf5, 0x7e, 0xf2, 0x20, 0xf9, 0x0a, 0xfb, 0x3d, 0x1e, 0x5c,
	0xb2, 0x70, 0xe9, 0x49, 0xc6, 0x83, 0xd2, 0x9d, 0x12, 0x68, 0x65, 0x79, 0xd4, 0x32, 0xea, 0x34,
	0x87, 0x91, 0x2b, 0x78, 0x36, 0x0c, 0x98, 0x64, 0x1e, 0x93, 0x38, 0x1a, 0x4c, 0x47, 0x14, 0xc5,
	0x8a, 0x07, 0x02, 0xff, 0x5d, 0xed, 0x25, 0xc0, 0x79, 0xc8, 0x6e, 0x3d, 0x89, 0xe9, 0xe2, 0x33,
	0x08, 0xf9, 0x69, 0x40, 0x3b, 0x66, 0x2f, 0xed, 0xe5, 0x9c, 0x77, 0x2b, 0x05, 0xef, 0x46, 0x1f,
	0xd7, 0x78, 0xdb, 0xa4, 0xf6, 0x75, 0x5c, 0xda, 0x7b, 0x50, 0x19, 0x84, 0xa1, 0x53, 0x53, 0x68,
	0x74, 0x24, 0x3d, 0xe8, 0x24, 0x3e, 0xd7, 0x23, 0xbf, 0x2d, 0x8c, 0xec, 0x64, 0x47, 0xce, 0x36,
	0x9e, 0x38, 0x7d, 0x06, 0x7b, 0x14, 0x17, 0x4c, 0x48, 0x0c, 0xcb, 0xb3, 0xe8, 0x80, 0x32, 0xe3,
	0x80, 0x22, 0x01, 0x74, 0xfa, 0x6c, 0x8e, 0x63, 0xb6, 0x79, 0x04, 0xe9, 0x1b, 0xa8, 0x9d, 0x23,
	0x86, 0x42, 0x7d, 0x9d, 0xcd, 0xe3, 0xfd, 0xf4, 0x01, 0x05, 0x0f, 0x83, 0x4b, 0x4e, 0xb7, 0x37,
	0xc8, 0x67, 0xb0, 0xb4, 0xf3, 0x4a, 0xab, 0x3d, 0x85, 0x1a, 0xe5, 0x5c, 0x0a, 0xed, 0xba, 0x6d,
	0x41, 0x7e, 0x18, 0xb0, 0x97, 0xfa, 0xad, 0x34, 0xf9, 0x73, 0xa8, 0xeb, 0x3d, 0x0a, 0xed, 0xb5,
	0xa4, 0x4e, 0xc7, 0xac, 0xfc, 0x75, 0xcc, 0xf7, 0xd0, 0x9e, 0x7d, 0xe9, 0xf3, 0xe0, 0x11, 0xad,
	0x90, 0x13, 0xb0, 0x72, 0x76, 0x29, 0x41, 0xf1, 0xdb, 0x84, 0x46, 0xd2, 0x9b, 0xde, 0x7d, 0xf4,
	0x6c, 0x4d, 0xfd, 0x38, 0xb9, 0xd0, 0x3c, 0x9d, 0x15, 0xf3, 0x33, 0x0b, 0xe5, 0xf3, 0xb5, 0x52,
	0xcc, 0xd7, 0xbc, 0x0b, 0xab, 0x45, 0x17, 0xde, 0x4f, 0xa0, 0xda, 0x03, 0x09, 0x94, 0x4d, 0xe9,
	0x9d, 0x5c, 0x4a, 0x47, 0xbb, 0xe8, 0xf7, 0x74, 0xee, 0xed, 0xaa, 0x5d, 0x27, 0xf5, 0x03, 0xc9,
	0x58, 0x7f, 0x30, 0x19, 0xdb, 0x60, 0x4e, 0x46, 0x4e, 0x43, 0xa5, 0x91, 0x39, 0x19, 0xe5, 0xf6,
	0x0b, 0x85, 0xfd, 0x16, 0x33, 0xac, 0x79, 0x3f, 0xc3, 0xec, 0x2e, 0x74, 0xf4, 0x7d, 0x8a, 0x73,
	0x64, 0xb7, 0xe8, 0x3b, 0x2d, 0x75, 0xad, 0x08, 0x5f, 0xec, 0xa8, 0xbf, 0x17, 0xef, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x18, 0x5d, 0xe2, 0xcc, 0x79, 0x08, 0x00, 0x00,
}
